// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnHij_BMoIo46ywUe71RpaB13sxJSpDk4',
    appId: '1:122662345955:web:b5c9adf3d5ba007bf0b9d6',
    messagingSenderId: '122662345955',
    projectId: 'intellect-connect-3d9fc',
    authDomain: 'intellect-connect-3d9fc.firebaseapp.com',
    storageBucket: 'intellect-connect-3d9fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkzTVLMb1CwiVPA8QyPLOsgKe3IeAY1Oo',
    appId: '1:122662345955:android:74e9412e728dd079f0b9d6',
    messagingSenderId: '122662345955',
    projectId: 'intellect-connect-3d9fc',
    storageBucket: 'intellect-connect-3d9fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIf40OwxNM2RwnaonLT2bePTqSiXtwHGM',
    appId: '1:122662345955:ios:4b074fb5183128bcf0b9d6',
    messagingSenderId: '122662345955',
    projectId: 'intellect-connect-3d9fc',
    storageBucket: 'intellect-connect-3d9fc.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIf40OwxNM2RwnaonLT2bePTqSiXtwHGM',
    appId: '1:122662345955:ios:4b074fb5183128bcf0b9d6',
    messagingSenderId: '122662345955',
    projectId: 'intellect-connect-3d9fc',
    storageBucket: 'intellect-connect-3d9fc.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnHij_BMoIo46ywUe71RpaB13sxJSpDk4',
    appId: '1:122662345955:web:7a32d5f0ffbc1926f0b9d6',
    messagingSenderId: '122662345955',
    projectId: 'intellect-connect-3d9fc',
    authDomain: 'intellect-connect-3d9fc.firebaseapp.com',
    storageBucket: 'intellect-connect-3d9fc.firebasestorage.app',
  );
}
